# Generated by Django 3.2.9 on 2022-01-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='código',
            field=models.CharField(max_length=100),
        ),
    ]
