# Generated by Django 3.2.9 on 2022-01-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_código'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='código',
            new_name='codigo',
        ),
    ]
