# Generated by Django 3.2.9 on 2022-01-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_rename_código_imovel_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
