# Generated by Django 3.2.9 on 2022-01-08 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('imoveis', '0007_rename_foto_imovel_foto_imovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Alugueis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_final', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('imóvel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
        ),
    ]
